import argparse as ap

from ppan import train, evaluate
from ppan.preprocessing import preprocess, pretrain


def main():
    parser = ap.ArgumentParser(
        prog="ppan",
        description="A model for analyzing piano playing videos and extracting "
                    "what notes are being played.",
        epilog="Coded with love by Uros Zivanovic"
    )
    subparsers = parser.add_subparsers(required=True)

    dataset_dir_args = ["-d", "--dataset-dir"]
    dataset_dir_kwargs = {
        "nargs": 1,
        "action": "store",
        "type": str,
        "help": "Path to dataset",
        "required": True
    }

    parser_train = subparsers.add_parser("train",
                                         help="Train the network on some "
                                              "data.")
    parser_train.add_argument(
        *dataset_dir_args,
        **dataset_dir_kwargs
    )
    parser_train.add_argument(
        "-o", "--output-dir",
        nargs=1,
        action="store",
        type=str,
        help="Where to save the trained model, full path with filename.",
        required=True,
    )
    parser_train.add_argument(
        "-t", "--tokenizer-dir",
        nargs=1,
        action="store",
        type=str,
        help="Location of pretrained tokenizer folder.",
        required=True
    )
    parser_train.add_argument(
        "-c", "--decoder-checkpoint",
        nargs=1,
        action="store",
        type=str,
        help="Location of pretrained decoder",
        required=True
    )
    parser_train.add_argument(
        "-r", "--checkpoint-dir",
        nargs=1,
        action="store",
        type=str,
        help="Location of a training checkpoint when continuing training.",
        required=False,
        default=None
    )
    parser_train.set_defaults(func=train.main)

    parser_eval = subparsers.add_parser("evaluate",
                                        help="Evaluate the model on a "
                                             "testset.")
    parser_eval.add_argument(
        *dataset_dir_args,
        **dataset_dir_kwargs
    )
    parser_eval.add_argument(
        "-m", "--model-checkpoint",
        nargs=1,
        action="store",
        type=str,
        help="Path to the saved model.",
        required=True
    )
    parser_eval.add_argument(
        "-o", "--output-dir",
        nargs=1,
        action="store",
        type=str,
        help="Where to save the trained model, full path with filename.",
        required=True,
    )
    parser_eval.add_argument(
        "-t", "--tokenizer-dir",
        nargs=1,
        action="store",
        type=str,
        help="Location of pretrained tokenizer folder.",
        required=True
    )
    parser_eval.set_defaults(func=evaluate.main)

    parser_preprocess = subparsers.add_parser(
        "preprocess",
        help="Perform preprocessing steps before training can be done.")
    parser_preprocess.add_argument(
        *dataset_dir_args,
        **dataset_dir_kwargs
    )
    parser_preprocess.add_argument(
        "-o", "--output-dir",
        nargs=1,
        action="store",
        type=str,
        help="Where to output preprocessed files",
        required=True
    )
    parser_preprocess.add_argument(
        "-n", "--dataset_name",
        required=False,
        nargs=1,
        action="store",
        type=str,
        help="When using splits, the names are autogenerated as train/test. "
             "If not splitting the name must be given manually."
    )
    parser_preprocess.set_defaults(func=preprocess.main)

    parser_pretrain = subparsers.add_parser(
        "pretrain",
        help="Perform pretraining steps to prepare the tokenizer and decoder.")
    parser_pretrain.add_argument(
        *dataset_dir_args,
        **dataset_dir_kwargs
    )
    parser_pretrain.add_argument(
        "-k", "--tokenizer",
        action="store_true",
        help="Whether to train the tokenizer. If not training tokenizer then "
             "output-dir is searched for an already trained one."
    )
    parser_pretrain.add_argument(
        "-m", "--decoder-model",
        action="store_true",
        help="Whether to train the decoder."
    )
    parser_pretrain.add_argument(
        "-o", "--output-dir",
        nargs=1,
        action="store",
        type=str,
        help="Where to save the trained tokenizer and decoder.",
        required=True
    )
    parser_pretrain.set_defaults(func=pretrain.main)

    args = parser.parse_args()
    args.func(**vars(args))


if __name__ == "__main__":
    main()
